mpdosmilcuatroGEH <- within(mpdosmilcuatroGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                             }
)
mpdosmilcuatroGEM <- within(mpdosmilcuatroGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilcincoGEH <- within(mpdosmilcuatroGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilcincoGEM <- within(mpdosmilcuatroGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilseisGEH <- within(mpdosmilseisGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilseisGEM <- within(mpdosmilseisGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilsieteGEH <- within(mpdosmilsieteGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilsieteGEM <- within(mpdosmilsieteGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilochoGEH <- within(mpdosmilochoGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilochoGEM <- within(mpdosmilochoGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilnueveGEH <- within(mpdosmilnueveGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilnueveGEM <- within(mpdosmilnueveGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmildiezGEH <- within(mpdosmildiezGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmildiezGEM <- within(mpdosmildiezGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilonceGEH <- within(mpdosmilonceGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilonceGEM <- within(mpdosmilonceGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmildoceGEH <- within(mpdosmildoceGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmildoceGEM <- within(mpdosmildoceGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmiltreceGEH <- within(mpdosmiltreceGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmiltreceGEM <- within(mpdosmiltreceGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilcatorceGEH <- within(mpdosmilcatorceGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilcatorceGEM <- within(mpdosmilcatorceGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilquinceGEH <- within(mpdosmilquinceGEH, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)
mpdosmilquinceGEM <- within(mpdosmilquinceGEM, 
                           {
                             #  Eliminar espacios en n??meros.
                             Mayor.a.uno <- gsub("[ ]", "", Mayor.a.uno)
                             Uno.a.Cuatro <- gsub("[ ]", "", Uno.a.Cuatro)
                             Cinco.a.Nueve <- gsub("[ ]", "", Cinco.a.Nueve)
                             Diez.a.Catorce <- gsub("[ ]", "",Diez.a.Catorce)
                             Quince.a.Diecinueve <- gsub("[ ]", "", Quince.a.Diecinueve)
                             Veinte.a.Veinticuatro <- gsub("[ ]", "", Veinte.a.Veinticuatro)
                             Veinticinco.a.Cuarentaycuatro <- gsub("[ ]", "", Veinticinco.a.Cuarentaycuatro)
                             CuarentayCinco.a.Cuarentaynueve <- gsub("[ ]", "", CuarentayCinco.a.Cuarentaynueve)
                             Cincuenta.a.Cincuentaynueve <- gsub("[ ]", "", Cincuenta.a.Cincuentaynueve)
                             Sesenta.a.Sesentaycuatro <- gsub("[ ]", "", Sesenta.a.Sesentaycuatro)
                             Mayor.a.Sesentaycinco <- gsub("[ ]", "", Mayor.a.Sesentaycinco)
                             No.se.reporto.la.edad <- gsub("[ ]", "", No.se.reporto.la.edad)
                             Total <- gsub("[ ]", "", Total)
                             Estado <- gsub("M.xico.*", "Mexico", Estado)
                             Estado <- gsub("Mich.*n.*", "Michoacan", Estado)
                             Estado <- gsub("Nuevo Le.*n.*", "Nuevo Leon", Estado)
                             Estado <- gsub("Quer.taro.*", "Queretaro", Estado)
                             Estado <- gsub("San Luis Pot.*.*", "San Luis Potosi", Estado)
                             Estado <- gsub("Yuca.*n.*", "Yucatan",Estado)
                           }
)


