setwd("/Users/rayangf/Desktop/MordedurasPerro/Data/CSV/GrupoDeEdad/General")
geg = list.files(pattern="*.csv") #Codigo para leer los csv GrupoDeEdad caso general
for (i in 1:length(geg)) assign(geg[i], read.csv(geg[i],colClasses = "character", 
                                                 na.strings = "#N/A"))
setwd("/Users/rayangf/Desktop/MordedurasPerro/Data/CSV/GrupoDeEdad/Hombres")
geh = list.files(pattern="*.csv") #Codigo para leer los csv GrupoDeEdad caso hombres
for (i in 1:length(geh)) assign(geh[i], read.csv(geh[i],colClasses = "character", 
                                                 na.strings = "#N/A"))
setwd("/Users/rayangf/Desktop/MordedurasPerro/Data/CSV/GrupoDeEdad/Mujeres")
gem = list.files(pattern="*.csv") #Codigo para leer los csv GrupoDeEdad caso mujeres
for (i in 1:length(gem)) assign(gem[i], read.csv(gem[i],colClasses = "character", 
                                                 na.strings = "#N/A"))

names(ge2004g.csv) <- toupper(names(get(geg[1])))
names(ge2005g.csv) <- toupper(names(get(geg[2])))
names(ge2006g.csv) <- toupper(names(get(geg[3])))
names(ge2007g.csv) <- toupper(names(get(geg[4])))
names(ge2008g.csv) <- toupper(names(get(geg[5])))
names(ge2009g.csv) <- toupper(names(get(geg[6])))
names(ge2010g.csv) <- toupper(names(get(geg[7])))
names(ge2011g.csv) <- toupper(names(get(geg[8])))
names(ge2012g.csv) <- toupper(names(get(geg[9])))
names(ge2013g.csv) <- toupper(names(get(geg[10])))
names(ge2014g.csv) <- toupper(names(get(geg[11])))
names(ge2015g.csv) <- toupper(names(get(geg[12])))
names(ge2004h.csv) <- toupper(names(get(geh[1])))
names(ge2005h.csv) <- toupper(names(get(geh[2])))
names(ge2006h.csv) <- toupper(names(get(geh[3])))
names(ge2007h.csv) <- toupper(names(get(geh[4])))
names(ge2008h.csv) <- toupper(names(get(geh[5])))
names(ge2009h.csv) <- toupper(names(get(geh[6])))
names(ge2010h.csv) <- toupper(names(get(geh[7])))
names(ge2011h.csv) <- toupper(names(get(geh[8])))
names(ge2012h.csv) <- toupper(names(get(geh[9])))
names(ge2013h.csv) <- toupper(names(get(geh[10])))
names(ge2014h.csv) <- toupper(names(get(geh[11])))
names(ge2015h.csv) <- toupper(names(get(geh[12])))
names(ge2004m.csv) <- toupper(names(get(gem[1])))
names(ge2005m.csv) <- toupper(names(get(gem[2])))
names(ge2006m.csv) <- toupper(names(get(gem[3])))
names(ge2007m.csv) <- toupper(names(get(gem[4])))
names(ge2008m.csv) <- toupper(names(get(gem[5])))
names(ge2009m.csv) <- toupper(names(get(gem[6])))
names(ge2010m.csv) <- toupper(names(get(gem[7])))
names(ge2011m.csv) <- toupper(names(get(gem[8])))
names(ge2012m.csv)<- toupper(names(get(gem[9])))
names(ge2013m.csv) <- toupper(names(get(gem[10])))
names(ge2014m.csv) <- toupper(names(get(gem[11])))
names(ge2015m.csv) <- toupper(names(get(gem[12])))

ge2004g.csv <- within(ge2004g.csv, 
                           {
                             #  Eliminar espacios en n??meros y arregla nombres de estados
                             MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                             UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                             CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                             DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                             QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                             VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                             VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                             CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                             CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                             SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                             MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                             NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                             TOTAL <- gsub("[ ]", "", TOTAL)
                             ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                             ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                             ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                             ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                             ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                             ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                             }
)
ge2005g.csv <- within(ge2005g.csv, 
                  {
                    MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                    UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                    CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                    DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                    QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                    VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                    VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                    CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                    CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                    SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                    MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                    NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                    TOTAL <- gsub("[ ]", "", TOTAL)
                    ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                    ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                    ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                    ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                    ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                    ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                  }
)
ge2006g.csv <- within(ge2006g.csv, 
                  {
                    MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                    UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                    CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                    DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                    QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                    VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                    VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                    CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                    CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                    SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                    MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                    NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                    TOTAL <- gsub("[ ]", "", TOTAL)
                    ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                    ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                    ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                    ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                    ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                    ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                  }
)

ge2007g.csv <- within(ge2007g.csv, 
                  {
                    MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                    UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                    CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                    DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                    QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                    VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                    VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                    CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                    CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                    SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                    MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                    NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                    TOTAL <- gsub("[ ]", "", TOTAL)
                    ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                    ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                    ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                    ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                    ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                    ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                  }
)

ge2008g.csv <- within(ge2008g.csv, 
                  {
                    MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                    UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                    CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                    DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                    QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                    VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                    VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                    CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                    CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                    SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                    MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                    NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                    TOTAL <- gsub("[ ]", "", TOTAL)
                    ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                    ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                    ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                    ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                    ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                    ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                  }
)

ge2009g.csv <- within(ge2009g.csv, 
                  {

                    MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                    UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                    CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                    DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                    QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                    VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                    VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                    CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                    CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                    SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                    MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                    NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                    TOTAL <- gsub("[ ]", "", TOTAL)
                    ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                    ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                    ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                    ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                    ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                    ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                  }
)


ge2010g.csv <- within(ge2010g.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)


ge2011g.csv <- within(ge2011g.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2012g.csv <- within(ge2012g.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2013g.csv <- within(ge2013g.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)


ge2014g.csv <- within(ge2014g.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)


ge2015g.csv <- within(ge2015g.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)


ge2004h.csv <- within(ge2004h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2005h.csv <- within(ge2005h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2006h.csv <- within(ge2006h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)


ge2007h.csv <- within(ge2007h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2008h.csv <- within(ge2008h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2009h.csv <- within(ge2009h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2010h.csv <- within(ge2010h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2011h.csv <- within(ge2011h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2012h.csv <- within(ge2012h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2013h.csv <- within(ge2013h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2014h.csv <- within(ge2014h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2015h.csv <- within(ge2015h.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2004m.csv <- within(ge2004m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2005m.csv <- within(ge2005m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2006m.csv <- within(ge2006m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)


ge2007m.csv <- within(ge2007m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2008m.csv <- within(ge2008m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2009m.csv <- within(ge2009m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2010m.csv <- within(ge2010m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)

ge2011m.csv <- within(ge2011m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2012m.csv <- within(ge2012m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2013m.csv <- within(ge2013m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2014m.csv <- within(ge2014m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
ge2015m.csv <- within(ge2015m.csv, 
                      {
                        MAYOR.A.UNO <- gsub("[ ]", "", MAYOR.A.UNO)
                        UNO.A.CUATRO <- gsub("[ ]", "", UNO.A.CUATRO)
                        CINCO.A.NUEVE <- gsub("[ ]", "", CINCO.A.NUEVE)
                        DIEZ.A.CATORCE <- gsub("[ ]", "",DIEZ.A.CATORCE)
                        QUINCE.A.DIECINUEVE <- gsub("[ ]", "", QUINCE.A.DIECINUEVE)
                        VEINTE.A.VEINTICUATRO <- gsub("[ ]", "", VEINTE.A.VEINTICUATRO )
                        VEINTICINCO.A.CUARENTAYCUATRO <- gsub("[ ]", "", VEINTICINCO.A.CUARENTAYCUATRO)
                        CUARENTAYCINCO.A.CUARENTAYNUEVE <- gsub("[ ]", "", CUARENTAYCINCO.A.CUARENTAYNUEVE)
                        CINCUENTA.A.CINCUENTAYNUEVE <- gsub("[ ]", "", CINCUENTA.A.CINCUENTAYNUEVE)
                        SESENTA.A.SESENTAYCUATRO <- gsub("[ ]", "", SESENTA.A.SESENTAYCUATRO)
                        MAYOR.A.SESENTAYCINCO <- gsub("[ ]", "", MAYOR.A.SESENTAYCINCO)
                        NO.SE.REPORTO.LA.EDAD <- gsub("[ ]", "", NO.SE.REPORTO.LA.EDAD)
                        TOTAL <- gsub("[ ]", "", TOTAL)
                        ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                        ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                        ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                        ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                        ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                        ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                      }
)
