setwd("/Users/rayangf/Desktop/MordedurasPerro/Data/CSV/FuenteDeNotificacion/General")
fng = list.files(pattern="*.csv") #Codigo para leer los csv FuenteDeNotificacion caso general
for (i in 1:length(fng)) assign(fng[i], read.csv(fng[i],colClasses = "character", 
                                                 na.strings = "#N/A"))

setwd("/Users/rayangf/Desktop/MordedurasPerro/Data/CSV/FuenteDeNotificacion/Hombres")
fnh = list.files(pattern="*.csv") #Codigo para leer los csv FuenteDeNotificacion caso hombres
for (i in 1:length(fnh)) assign(fnh[i], read.csv(fnh[i],colClasses = "character", 
                                                 na.strings = "#N/A"))

setwd("/Users/rayangf/Desktop/MordedurasPerro/Data/CSV/FuenteDeNotificacion/Mujeres")
fnm = list.files(pattern="*.csv") #Codigo para leer los csv FuenteDeNotificacion caso mujeres
for (i in 1:length(fnm)) assign(fnm[i], read.csv(fnm[i],colClasses = "character", 
                                                 na.strings = "#N/A"))

names(fn2004g.csv) <- toupper(names(get(fng[1])))
names(fn2005g.csv) <- toupper(names(get(fng[2])))
names(fn2006g.csv) <- toupper(names(get(fng[3])))
names(fn2007g.csv) <- toupper(names(get(fng[4])))
names(fn2008g.csv) <- toupper(names(get(fng[5])))
names(fn2009g.csv) <- toupper(names(get(fng[6])))
names(fn2010g.csv) <- toupper(names(get(fng[7])))
names(fn2011g.csv) <- toupper(names(get(fng[8])))
names(fn2012g.csv) <- toupper(names(get(fng[9])))
names(fn2013g.csv) <- toupper(names(get(fng[10])))
names(fn2014g.csv) <- toupper(names(get(fng[11])))
names(fn2015g.csv) <- toupper(names(get(fng[12])))
names(fn2004h.csv) <- toupper(names(get(fnh[1])))
names(fn2005h.csv) <- toupper(names(get(fnh[2])))
names(fn2006h.csv) <- toupper(names(get(fnh[3])))
names(fn2007h.csv) <- toupper(names(get(fnh[4])))
names(fn2008h.csv) <- toupper(names(get(fnh[5])))
names(fn2009h.csv) <- toupper(names(get(fnh[6])))
names(fn2010h.csv) <- toupper(names(get(fnh[7])))
names(fn2011h.csv) <- toupper(names(get(fnh[8])))
names(fn2012h.csv) <- toupper(names(get(fnh[9])))
names(fn2013h.csv) <- toupper(names(get(fnh[10])))
names(fn2014h.csv) <- toupper(names(get(fnh[11])))
names(fn2015h.csv) <- toupper(names(get(fnh[12])))
names(fn2004m.csv) <- toupper(names(get(fnm[1])))
names(fn2005m.csv) <- toupper(names(get(fnm[2])))
names(fn2006m.csv) <- toupper(names(get(fnm[3])))
names(fn2007m.csv) <- toupper(names(get(fnm[4])))
names(fn2008m.csv) <- toupper(names(get(fnm[5])))
names(fn2009m.csv) <- toupper(names(get(fnm[6])))
names(fn2010m.csv) <- toupper(names(get(fnm[7])))
names(fn2011m.csv) <- toupper(names(get(fnm[8])))
names(fn2012m.csv)<- toupper(names(get(fnm[9])))
names(fn2013m.csv) <- toupper(names(get(fnm[10])))
names(fn2014m.csv) <- toupper(names(get(fnm[11])))
names(fn2015m.csv) <- toupper(names(get(fnm[12])))


fn2004g.csv  <- within(fn2004g.csv , 
                          {
                            #  Eliminar espacios en números.
                            SALUD <- gsub("[ ]", "", SALUD)
                            IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                            ISSSTE <- gsub("[ ]", "", ISSSTE)
                            IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                            DIF <- gsub("[ ]", "", DIF)
                            PEMEX <- gsub("[ ]", "", PEMEX)
                            SEDENA <- gsub("[ ]", "", SEDENA)
                            SEMAR <- gsub("[ ]", "", SEMAR)
                            OTRAS <- gsub("[ ]", "", OTRAS)
                            TOTAL <- gsub("[ ]", "", TOTAL)
                            #  Sustituye N.A. y S/R por cero.
                            IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                            SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                            ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                            IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                            DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                            PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                            SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                            SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                            OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                            TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                            #  Completa nombres estados.
                            ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                            ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                            ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                            ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                            ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                            ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                          }
)
fn2005g.csv  <- within(fn2005g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2006g.csv  <- within(fn2006g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2007g.csv  <- within(fn2007g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2008g.csv  <- within(fn2008g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2009g.csv  <- within(fn2009g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2010g.csv  <- within(fn2010g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2011g.csv  <- within(fn2011g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2012g.csv  <- within(fn2012g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2013g.csv  <- within(fn2013g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2014g.csv  <- within(fn2014g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2015g.csv  <- within(fn2015g.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)

fn2004h.csv  <- within(fn2004h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2005h.csv  <- within(fn2005h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2006h.csv  <- within(fn2006h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2007h.csv  <- within(fn2007h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2008h.csv  <- within(fn2008h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2009h.csv  <- within(fn2009h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2010h.csv  <- within(fn2010h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2011h.csv  <- within(fn2011h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2012h.csv  <- within(fn2012h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2013h.csv  <- within(fn2013h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2014h.csv  <- within(fn2014h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2015h.csv  <- within(fn2015h.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)

fn2004m.csv  <- within(fn2004m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2005m.csv  <- within(fn2005m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2006m.csv  <- within(fn2006m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2007m.csv  <- within(fn2007m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2008m.csv  <- within(fn2008m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2009m.csv  <- within(fn2009m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2010m.csv  <- within(fn2010m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2011m.csv  <- within(fn2011m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2012m.csv  <- within(fn2012m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2013m.csv  <- within(fn2013m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2014m.csv  <- within(fn2014m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)
fn2015m.csv  <- within(fn2015m.csv , 
                       {
                         #  Eliminar espacios en números.
                         SALUD <- gsub("[ ]", "", SALUD)
                         IMSS.ORD <- gsub("[ ]", "", IMSS.ORD)
                         ISSSTE <- gsub("[ ]", "", ISSSTE)
                         IMSS.OP <- gsub("[ ]", "",IMSS.OP)
                         DIF <- gsub("[ ]", "", DIF)
                         PEMEX <- gsub("[ ]", "", PEMEX)
                         SEDENA <- gsub("[ ]", "", SEDENA)
                         SEMAR <- gsub("[ ]", "", SEMAR)
                         OTRAS <- gsub("[ ]", "", OTRAS)
                         TOTAL <- gsub("[ ]", "", TOTAL)
                         #  Sustituye N.A. y S/R por cero.
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA", IMSS.OP)
                         SALUD <- gsub("N.A.*|S.R*", "NA", SALUD)
                         ISSSTE <- gsub("N.A.*|S.R*", "NA", ISSSTE)
                         IMSS.OP <- gsub("N.A.*|S.R*", "NA",IMSS.OP)
                         DIF <- gsub("N.A.*|S.R*", "NA", DIF)
                         PEMEX <- gsub("N.A.*|S.R*", "NA", PEMEX)
                         SEDENA <- gsub("N.A.*|S.R*", "NA", SEDENA)
                         SEMAR <- gsub("N.A.*|S.R*", "NA", SEMAR)
                         OTRAS <- gsub("N.A.*|S.R*", "NA", OTRAS)
                         TOTAL <- gsub("N.A.*|S.R*", "NA", TOTAL)
                         #  Completa nombres estados.
                         ESTADO <- gsub("M.xico.*", "Mexico", ESTADO)
                         ESTADO <- gsub("Mich.*n.*", "Michoacan", ESTADO)
                         ESTADO <- gsub("Nuevo Le.*n.*", "Nuevo Leon", ESTADO)
                         ESTADO <- gsub("Quer.taro.*", "Queretaro", ESTADO)
                         ESTADO <- gsub("San Luis Pot.*.*", "San Luis Potosi", ESTADO)
                         ESTADO <- gsub("Yuca.*n.*", "Yucatan",ESTADO)
                       }
)

